### ISSUE TITLE
Can't build Embedded example

### ISSUE THREAD

**Issue by bestwnh** [sliemeobn/elementary-dom#6]
Run ./build.sh, got error in screenshot. Need some help.
<img width="807" alt="image" src="https://github.com/user-attachments/assets/8bc81af0-8f88-40a5-b896-47ef6aac80b1">
If I run it again, the first error gone. But last one remain.
<img width="810" alt="image" src="https://github.com/user-attachments/assets/2b69bfae-d10f-440e-85b0-fa7ebf32868d">

**Comment by sliemeobn** [comment]
can you verify that you are running it with a recent developer toolchain?

`swift --version`
should be something like `Apple Swift version 6.1-dev (LLVM 89ccf4b8a46135a, Swift 6a5ae8d5df144dd)`

**Comment by bestwnh** [comment]
@sliemeobn I'm using a swift 6.0 from https://github.com/swiftwasm/swift/releases.
So where I can find a 6.1 dev snapshot?

**Comment by sliemeobn** [comment]
you don‘t need a wasm/wasi SDK or toolchain, just a plain Swift toolchain from swift.org.

**Comment by bestwnh** [comment]
Change to swift 6.1 snapshot and run `swift package update` make it work. Just need some guide in the readme.
